### PR TITLE
Compatible for Slate 0.32 

### PR DESCRIPTION
**Pull request by zhujinxuan**
Just like https://github.com/GitbookIO/slate-edit-table/pull/59

### CODE REVIEW

**Comment by zhujinxuan** [comment]
@Soreine  Updated at https://github.com/GitbookIO/slate-edit-table/pull/59#pullrequestreview-87447552 .  It is about the npm function differently between `peerDependency` and `dependency`. 
Then it is about the choice between changing package.json in `eslint-config-gitbook` or changing package.json in `slate-edit-*`

**Comment by zhujinxuan** [comment]
Remove prettier packages in recent commit.  However, packages like `eslint-plugin-prettier` cannot be installed by `yarn install` or `yarn install --peer`

**Comment by zhujinxuan** [comment]
Recent commits in PR updates the babel config according to the recent changes in Slate 
https://github.com/ianstormtaylor/slate/pull/1557

**Comment by Soreine** [comment]
Same comments than on GitbookIO/slate-edit-table#59
I'll keep the extra devDependencies

**Comment by Soreine** [comment]
Thank you very much @zhujinxuan

**Pull request merged**
